// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.1
// source: order.proto

package orderpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderService_CreateOffer_FullMethodName                    = "/order.OrderService/CreateOffer"
	OrderService_GetOffer_FullMethodName                       = "/order.OrderService/GetOffer"
	OrderService_ListOffers_FullMethodName                     = "/order.OrderService/ListOffers"
	OrderService_AcceptOffer_FullMethodName                    = "/order.OrderService/AcceptOffer"
	OrderService_RejectOffer_FullMethodName                    = "/order.OrderService/RejectOffer"
	OrderService_CancelOffer_FullMethodName                    = "/order.OrderService/CancelOffer"
	OrderService_GetTransaction_FullMethodName                 = "/order.OrderService/GetTransaction"
	OrderService_ListTransactions_FullMethodName               = "/order.OrderService/ListTransactions"
	OrderService_UpdateTransactionStatus_FullMethodName        = "/order.OrderService/UpdateTransactionStatus"
	OrderService_GetFinanceOverview_FullMethodName             = "/order.OrderService/GetFinanceOverview"
	OrderService_ListPlatformFees_FullMethodName               = "/order.OrderService/ListPlatformFees"
	OrderService_GetPlatformWallet_FullMethodName              = "/order.OrderService/GetPlatformWallet"
	OrderService_ListPlatformWalletTransactions_FullMethodName = "/order.OrderService/ListPlatformWalletTransactions"
	OrderService_CollectFee_FullMethodName                     = "/order.OrderService/CollectFee"
	OrderService_CreateEscrow_FullMethodName                   = "/order.OrderService/CreateEscrow"
	OrderService_ListEscrows_FullMethodName                    = "/order.OrderService/ListEscrows"
	OrderService_ReleaseEscrow_FullMethodName                  = "/order.OrderService/ReleaseEscrow"
	OrderService_GetSellerWallet_FullMethodName                = "/order.OrderService/GetSellerWallet"
	OrderService_ListSellerWalletTransactions_FullMethodName   = "/order.OrderService/ListSellerWalletTransactions"
	OrderService_CreateWithdrawal_FullMethodName               = "/order.OrderService/CreateWithdrawal"
	OrderService_ListSellerWithdrawals_FullMethodName          = "/order.OrderService/ListSellerWithdrawals"
	OrderService_ListWithdrawals_FullMethodName                = "/order.OrderService/ListWithdrawals"
	OrderService_ApproveWithdrawal_FullMethodName              = "/order.OrderService/ApproveWithdrawal"
	OrderService_RejectWithdrawal_FullMethodName               = "/order.OrderService/RejectWithdrawal"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*Offer, error)
	GetOffer(ctx context.Context, in *GetOfferRequest, opts ...grpc.CallOption) (*Offer, error)
	ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error)
	AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*Transaction, error)
	RejectOffer(ctx context.Context, in *RejectOfferRequest, opts ...grpc.CallOption) (*Offer, error)
	CancelOffer(ctx context.Context, in *CancelOfferRequest, opts ...grpc.CallOption) (*Offer, error)
	GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error)
	ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error)
	UpdateTransactionStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*Transaction, error)
	GetFinanceOverview(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FinanceOverview, error)
	ListPlatformFees(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListPlatformFeesResponse, error)
	GetPlatformWallet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlatformWallet, error)
	ListPlatformWalletTransactions(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListPlatformWalletTransactionsResponse, error)
	CollectFee(ctx context.Context, in *CollectFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error)
	CreateEscrow(ctx context.Context, in *CreateEscrowRequest, opts ...grpc.CallOption) (*EscrowTransaction, error)
	ListEscrows(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListEscrowsResponse, error)
	ReleaseEscrow(ctx context.Context, in *ReleaseEscrowRequest, opts ...grpc.CallOption) (*EscrowTransaction, error)
	GetSellerWallet(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*SellerWallet, error)
	ListSellerWalletTransactions(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*ListSellerWalletTransactionsResponse, error)
	CreateWithdrawal(ctx context.Context, in *CreateWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error)
	ListSellerWithdrawals(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*ListWithdrawalsResponse, error)
	ListWithdrawals(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListWithdrawalsResponse, error)
	ApproveWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error)
	RejectWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOffer(ctx context.Context, in *CreateOfferRequest, opts ...grpc.CallOption) (*Offer, error) {
	out := new(Offer)
	err := c.cc.Invoke(ctx, OrderService_CreateOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetOffer(ctx context.Context, in *GetOfferRequest, opts ...grpc.CallOption) (*Offer, error) {
	out := new(Offer)
	err := c.cc.Invoke(ctx, OrderService_GetOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListOffers(ctx context.Context, in *ListOffersRequest, opts ...grpc.CallOption) (*ListOffersResponse, error) {
	out := new(ListOffersResponse)
	err := c.cc.Invoke(ctx, OrderService_ListOffers_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) AcceptOffer(ctx context.Context, in *AcceptOfferRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, OrderService_AcceptOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RejectOffer(ctx context.Context, in *RejectOfferRequest, opts ...grpc.CallOption) (*Offer, error) {
	out := new(Offer)
	err := c.cc.Invoke(ctx, OrderService_RejectOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CancelOffer(ctx context.Context, in *CancelOfferRequest, opts ...grpc.CallOption) (*Offer, error) {
	out := new(Offer)
	err := c.cc.Invoke(ctx, OrderService_CancelOffer_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetTransaction(ctx context.Context, in *GetTransactionRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, OrderService_GetTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListTransactions(ctx context.Context, in *ListTransactionsRequest, opts ...grpc.CallOption) (*ListTransactionsResponse, error) {
	out := new(ListTransactionsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) UpdateTransactionStatus(ctx context.Context, in *UpdateStatusRequest, opts ...grpc.CallOption) (*Transaction, error) {
	out := new(Transaction)
	err := c.cc.Invoke(ctx, OrderService_UpdateTransactionStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetFinanceOverview(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*FinanceOverview, error) {
	out := new(FinanceOverview)
	err := c.cc.Invoke(ctx, OrderService_GetFinanceOverview_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListPlatformFees(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListPlatformFeesResponse, error) {
	out := new(ListPlatformFeesResponse)
	err := c.cc.Invoke(ctx, OrderService_ListPlatformFees_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetPlatformWallet(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PlatformWallet, error) {
	out := new(PlatformWallet)
	err := c.cc.Invoke(ctx, OrderService_GetPlatformWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListPlatformWalletTransactions(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListPlatformWalletTransactionsResponse, error) {
	out := new(ListPlatformWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListPlatformWalletTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CollectFee(ctx context.Context, in *CollectFeeRequest, opts ...grpc.CallOption) (*CollectFeeResponse, error) {
	out := new(CollectFeeResponse)
	err := c.cc.Invoke(ctx, OrderService_CollectFee_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateEscrow(ctx context.Context, in *CreateEscrowRequest, opts ...grpc.CallOption) (*EscrowTransaction, error) {
	out := new(EscrowTransaction)
	err := c.cc.Invoke(ctx, OrderService_CreateEscrow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListEscrows(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListEscrowsResponse, error) {
	out := new(ListEscrowsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListEscrows_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ReleaseEscrow(ctx context.Context, in *ReleaseEscrowRequest, opts ...grpc.CallOption) (*EscrowTransaction, error) {
	out := new(EscrowTransaction)
	err := c.cc.Invoke(ctx, OrderService_ReleaseEscrow_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetSellerWallet(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*SellerWallet, error) {
	out := new(SellerWallet)
	err := c.cc.Invoke(ctx, OrderService_GetSellerWallet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListSellerWalletTransactions(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*ListSellerWalletTransactionsResponse, error) {
	out := new(ListSellerWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListSellerWalletTransactions_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) CreateWithdrawal(ctx context.Context, in *CreateWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error) {
	out := new(WithdrawalRequest)
	err := c.cc.Invoke(ctx, OrderService_CreateWithdrawal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListSellerWithdrawals(ctx context.Context, in *SellerRequest, opts ...grpc.CallOption) (*ListWithdrawalsResponse, error) {
	out := new(ListWithdrawalsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListSellerWithdrawals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ListWithdrawals(ctx context.Context, in *PageRequest, opts ...grpc.CallOption) (*ListWithdrawalsResponse, error) {
	out := new(ListWithdrawalsResponse)
	err := c.cc.Invoke(ctx, OrderService_ListWithdrawals_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ApproveWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error) {
	out := new(WithdrawalRequest)
	err := c.cc.Invoke(ctx, OrderService_ApproveWithdrawal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) RejectWithdrawal(ctx context.Context, in *ProcessWithdrawalRequest, opts ...grpc.CallOption) (*WithdrawalRequest, error) {
	out := new(WithdrawalRequest)
	err := c.cc.Invoke(ctx, OrderService_RejectWithdrawal_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility
type OrderServiceServer interface {
	CreateOffer(context.Context, *CreateOfferRequest) (*Offer, error)
	GetOffer(context.Context, *GetOfferRequest) (*Offer, error)
	ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error)
	AcceptOffer(context.Context, *AcceptOfferRequest) (*Transaction, error)
	RejectOffer(context.Context, *RejectOfferRequest) (*Offer, error)
	CancelOffer(context.Context, *CancelOfferRequest) (*Offer, error)
	GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error)
	ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error)
	UpdateTransactionStatus(context.Context, *UpdateStatusRequest) (*Transaction, error)
	GetFinanceOverview(context.Context, *Empty) (*FinanceOverview, error)
	ListPlatformFees(context.Context, *PageRequest) (*ListPlatformFeesResponse, error)
	GetPlatformWallet(context.Context, *Empty) (*PlatformWallet, error)
	ListPlatformWalletTransactions(context.Context, *PageRequest) (*ListPlatformWalletTransactionsResponse, error)
	CollectFee(context.Context, *CollectFeeRequest) (*CollectFeeResponse, error)
	CreateEscrow(context.Context, *CreateEscrowRequest) (*EscrowTransaction, error)
	ListEscrows(context.Context, *PageRequest) (*ListEscrowsResponse, error)
	ReleaseEscrow(context.Context, *ReleaseEscrowRequest) (*EscrowTransaction, error)
	GetSellerWallet(context.Context, *SellerRequest) (*SellerWallet, error)
	ListSellerWalletTransactions(context.Context, *SellerRequest) (*ListSellerWalletTransactionsResponse, error)
	CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*WithdrawalRequest, error)
	ListSellerWithdrawals(context.Context, *SellerRequest) (*ListWithdrawalsResponse, error)
	ListWithdrawals(context.Context, *PageRequest) (*ListWithdrawalsResponse, error)
	ApproveWithdrawal(context.Context, *ProcessWithdrawalRequest) (*WithdrawalRequest, error)
	RejectWithdrawal(context.Context, *ProcessWithdrawalRequest) (*WithdrawalRequest, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (UnimplementedOrderServiceServer) CreateOffer(context.Context, *CreateOfferRequest) (*Offer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOffer not implemented")
}
func (UnimplementedOrderServiceServer) GetOffer(context.Context, *GetOfferRequest) (*Offer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOffer not implemented")
}
func (UnimplementedOrderServiceServer) ListOffers(context.Context, *ListOffersRequest) (*ListOffersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOffers not implemented")
}
func (UnimplementedOrderServiceServer) AcceptOffer(context.Context, *AcceptOfferRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptOffer not implemented")
}
func (UnimplementedOrderServiceServer) RejectOffer(context.Context, *RejectOfferRequest) (*Offer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectOffer not implemented")
}
func (UnimplementedOrderServiceServer) CancelOffer(context.Context, *CancelOfferRequest) (*Offer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelOffer not implemented")
}
func (UnimplementedOrderServiceServer) GetTransaction(context.Context, *GetTransactionRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransaction not implemented")
}
func (UnimplementedOrderServiceServer) ListTransactions(context.Context, *ListTransactionsRequest) (*ListTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransactions not implemented")
}
func (UnimplementedOrderServiceServer) UpdateTransactionStatus(context.Context, *UpdateStatusRequest) (*Transaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransactionStatus not implemented")
}
func (UnimplementedOrderServiceServer) GetFinanceOverview(context.Context, *Empty) (*FinanceOverview, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFinanceOverview not implemented")
}
func (UnimplementedOrderServiceServer) ListPlatformFees(context.Context, *PageRequest) (*ListPlatformFeesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlatformFees not implemented")
}
func (UnimplementedOrderServiceServer) GetPlatformWallet(context.Context, *Empty) (*PlatformWallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlatformWallet not implemented")
}
func (UnimplementedOrderServiceServer) ListPlatformWalletTransactions(context.Context, *PageRequest) (*ListPlatformWalletTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPlatformWalletTransactions not implemented")
}
func (UnimplementedOrderServiceServer) CollectFee(context.Context, *CollectFeeRequest) (*CollectFeeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CollectFee not implemented")
}
func (UnimplementedOrderServiceServer) CreateEscrow(context.Context, *CreateEscrowRequest) (*EscrowTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEscrow not implemented")
}
func (UnimplementedOrderServiceServer) ListEscrows(context.Context, *PageRequest) (*ListEscrowsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEscrows not implemented")
}
func (UnimplementedOrderServiceServer) ReleaseEscrow(context.Context, *ReleaseEscrowRequest) (*EscrowTransaction, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseEscrow not implemented")
}
func (UnimplementedOrderServiceServer) GetSellerWallet(context.Context, *SellerRequest) (*SellerWallet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellerWallet not implemented")
}
func (UnimplementedOrderServiceServer) ListSellerWalletTransactions(context.Context, *SellerRequest) (*ListSellerWalletTransactionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSellerWalletTransactions not implemented")
}
func (UnimplementedOrderServiceServer) CreateWithdrawal(context.Context, *CreateWithdrawalRequest) (*WithdrawalRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateWithdrawal not implemented")
}
func (UnimplementedOrderServiceServer) ListSellerWithdrawals(context.Context, *SellerRequest) (*ListWithdrawalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSellerWithdrawals not implemented")
}
func (UnimplementedOrderServiceServer) ListWithdrawals(context.Context, *PageRequest) (*ListWithdrawalsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListWithdrawals not implemented")
}
func (UnimplementedOrderServiceServer) ApproveWithdrawal(context.Context, *ProcessWithdrawalRequest) (*WithdrawalRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApproveWithdrawal not implemented")
}
func (UnimplementedOrderServiceServer) RejectWithdrawal(context.Context, *ProcessWithdrawalRequest) (*WithdrawalRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RejectWithdrawal not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOffer(ctx, req.(*CreateOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetOffer(ctx, req.(*GetOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListOffers(ctx, req.(*ListOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_AcceptOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).AcceptOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_AcceptOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).AcceptOffer(ctx, req.(*AcceptOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_RejectOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).RejectOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_RejectOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).RejectOffer(ctx, req.(*RejectOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CancelOffer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOfferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CancelOffer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CancelOffer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CancelOffer(ctx, req.(*CancelOfferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetTransaction(ctx, req.(*GetTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListTransactions(ctx, req.(*ListTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_UpdateTransactionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).UpdateTransactionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_UpdateTransactionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).UpdateTransactionStatus(ctx, req.(*UpdateStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetFinanceOverview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetFinanceOverview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetFinanceOverview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetFinanceOverview(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListPlatformFees_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListPlatformFees(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListPlatformFees_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListPlatformFees(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetPlatformWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetPlatformWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetPlatformWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetPlatformWallet(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListPlatformWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListPlatformWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListPlatformWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListPlatformWalletTransactions(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CollectFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectFeeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CollectFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CollectFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CollectFee(ctx, req.(*CollectFeeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateEscrow(ctx, req.(*CreateEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListEscrows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListEscrows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListEscrows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListEscrows(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ReleaseEscrow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseEscrowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ReleaseEscrow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ReleaseEscrow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ReleaseEscrow(ctx, req.(*ReleaseEscrowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetSellerWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetSellerWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetSellerWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetSellerWallet(ctx, req.(*SellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListSellerWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListSellerWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListSellerWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListSellerWalletTransactions(ctx, req.(*SellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_CreateWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateWithdrawal(ctx, req.(*CreateWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListSellerWithdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SellerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListSellerWithdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListSellerWithdrawals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListSellerWithdrawals(ctx, req.(*SellerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ListWithdrawals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ListWithdrawals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ListWithdrawals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ListWithdrawals(ctx, req.(*PageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ApproveWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ApproveWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ApproveWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ApproveWithdrawal(ctx, req.(*ProcessWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_RejectWithdrawal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWithdrawalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).RejectWithdrawal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_RejectWithdrawal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).RejectWithdrawal(ctx, req.(*ProcessWithdrawalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOffer",
			Handler:    _OrderService_CreateOffer_Handler,
		},
		{
			MethodName: "GetOffer",
			Handler:    _OrderService_GetOffer_Handler,
		},
		{
			MethodName: "ListOffers",
			Handler:    _OrderService_ListOffers_Handler,
		},
		{
			MethodName: "AcceptOffer",
			Handler:    _OrderService_AcceptOffer_Handler,
		},
		{
			MethodName: "RejectOffer",
			Handler:    _OrderService_RejectOffer_Handler,
		},
		{
			MethodName: "CancelOffer",
			Handler:    _OrderService_CancelOffer_Handler,
		},
		{
			MethodName: "GetTransaction",
			Handler:    _OrderService_GetTransaction_Handler,
		},
		{
			MethodName: "ListTransactions",
			Handler:    _OrderService_ListTransactions_Handler,
		},
		{
			MethodName: "UpdateTransactionStatus",
			Handler:    _OrderService_UpdateTransactionStatus_Handler,
		},
		{
			MethodName: "GetFinanceOverview",
			Handler:    _OrderService_GetFinanceOverview_Handler,
		},
		{
			MethodName: "ListPlatformFees",
			Handler:    _OrderService_ListPlatformFees_Handler,
		},
		{
			MethodName: "GetPlatformWallet",
			Handler:    _OrderService_GetPlatformWallet_Handler,
		},
		{
			MethodName: "ListPlatformWalletTransactions",
			Handler:    _OrderService_ListPlatformWalletTransactions_Handler,
		},
		{
			MethodName: "CollectFee",
			Handler:    _OrderService_CollectFee_Handler,
		},
		{
			MethodName: "CreateEscrow",
			Handler:    _OrderService_CreateEscrow_Handler,
		},
		{
			MethodName: "ListEscrows",
			Handler:    _OrderService_ListEscrows_Handler,
		},
		{
			MethodName: "ReleaseEscrow",
			Handler:    _OrderService_ReleaseEscrow_Handler,
		},
		{
			MethodName: "GetSellerWallet",
			Handler:    _OrderService_GetSellerWallet_Handler,
		},
		{
			MethodName: "ListSellerWalletTransactions",
			Handler:    _OrderService_ListSellerWalletTransactions_Handler,
		},
		{
			MethodName: "CreateWithdrawal",
			Handler:    _OrderService_CreateWithdrawal_Handler,
		},
		{
			MethodName: "ListSellerWithdrawals",
			Handler:    _OrderService_ListSellerWithdrawals_Handler,
		},
		{
			MethodName: "ListWithdrawals",
			Handler:    _OrderService_ListWithdrawals_Handler,
		},
		{
			MethodName: "ApproveWithdrawal",
			Handler:    _OrderService_ApproveWithdrawal_Handler,
		},
		{
			MethodName: "RejectWithdrawal",
			Handler:    _OrderService_RejectWithdrawal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
